### ISSUE TITLE
Prepend & Append

### ISSUE THREAD

**Issue by bmict** [bmict/netpyma#3]
Add Prepend and Append features for adding raw config lines before first line and after last line.

e.g:

```yml
prepend: ...
...
append: ...
```
